# Generated by Django 5.2.6 on 2025-09-04 10:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_contact', models.CharField(blank=True, max_length=50)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('suv', 'SUV'), ('truck', 'Truck'), ('motorcycle', 'Motorcycle'), ('van', 'Van'), ('bus', 'Bus'), ('other', 'Other')], default='car', max_length=20)),
                ('vehicle_brand', models.CharField(blank=True, max_length=50)),
                ('vehicle_model', models.CharField(blank=True, max_length=50)),
                ('vehicle_color', models.CharField(blank=True, max_length=30)),
                ('access_level', models.CharField(choices=[('full', 'Full Access'), ('limited', 'Limited Access'), ('visitor', 'Visitor Access'), ('emergency', 'Emergency Access')], default='full', max_length=20)),
                ('registered_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-registered_date'],
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20)),
                ('authorized', models.BooleanField()),
                ('confidence', models.FloatField()),
                ('gate_action', models.CharField(choices=[('opened', 'Gate Opened'), ('denied', 'Access Denied'), ('manual_open', 'Manual Override'), ('error', 'System Error')], max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner_info', models.JSONField(blank=True, default=dict)),
                ('detection_image', models.ImageField(blank=True, null=True, upload_to='detections/')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle_control.authorizedvehicle')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GateControlLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('open', 'Gate Opened'), ('close', 'Gate Closed'), ('auto_close', 'Auto Close'), ('manual_override', 'Manual Override'), ('emergency_open', 'Emergency Open'), ('maintenance', 'Maintenance Mode')], max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('related_access_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle_control.accesslog')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_name', models.CharField(max_length=100, unique=True)),
                ('setting_value', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('is_premium', models.BooleanField(default=False)),
                ('subscription_end_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='videos/')),
                ('plate_text', models.CharField(blank=True, max_length=50)),
                ('vehicle_type', models.CharField(blank=True, max_length=50)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error'), ('authorized', 'Authorized'), ('unauthorized', 'Unauthorized')], default='processing', max_length=20)),
                ('detection_image', models.ImageField(blank=True, null=True, upload_to='detections/')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('upload_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('processing_notes', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload_timestamp'],
            },
        ),
    ]
