# Generated by Django 5.2.6 on 2025-11-26 15:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_control', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gatecontrollog',
            name='related_access_log',
        ),
        migrations.RemoveField(
            model_name='authorizedvehicle',
            name='registered_by',
        ),
        migrations.RemoveField(
            model_name='gatecontrollog',
            name='triggered_by',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='vehicledetection',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_premium',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='subscription_end_date',
        ),
        migrations.CreateModel(
            name='RegisteredLicensePlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20)),
                ('plate_image', models.ImageField(upload_to='registered_plates/')),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('suv', 'SUV'), ('truck', 'Truck'), ('motorcycle', 'Motorcycle'), ('van', 'Van'), ('bus', 'Bus'), ('other', 'Other')], default='car', max_length=20)),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_contact', models.CharField(blank=True, max_length=50)),
                ('vehicle_brand', models.CharField(blank=True, max_length=50)),
                ('vehicle_model', models.CharField(blank=True, max_length=50)),
                ('vehicle_color', models.CharField(blank=True, max_length=30)),
                ('registered_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_plates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registered License Plate',
                'verbose_name_plural': 'Registered License Plates',
                'ordering': ['-registered_date'],
            },
        ),
        migrations.CreateModel(
            name='VideoDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='videos/')),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], default='processing', max_length=20)),
                ('upload_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_notes', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Video Detection',
                'verbose_name_plural': 'Video Detections',
                'ordering': ['-upload_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UnknownLicensePlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_plate_number', models.CharField(max_length=20)),
                ('detection_image', models.ImageField(upload_to='detections/unknown/')),
                ('confidence_score', models.FloatField()),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('frame_number', models.IntegerField(blank=True, null=True)),
                ('timestamp_seconds', models.FloatField(blank=True, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=50)),
                ('video_detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unknown_plates', to='vehicle_control.videodetection')),
            ],
            options={
                'verbose_name': 'Unknown License Plate Detection',
                'verbose_name_plural': 'Unknown License Plate Detections',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='KnownLicensePlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_plate_number', models.CharField(max_length=20)),
                ('detection_image', models.ImageField(upload_to='detections/known/')),
                ('confidence_score', models.FloatField()),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('frame_number', models.IntegerField(blank=True, null=True)),
                ('timestamp_seconds', models.FloatField(blank=True, null=True)),
                ('registered_plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_detections', to='vehicle_control.registeredlicenseplate')),
                ('video_detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='known_plates', to='vehicle_control.videodetection')),
            ],
            options={
                'verbose_name': 'Known License Plate Detection',
                'verbose_name_plural': 'Known License Plate Detections',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.DeleteModel(
            name='AccessLog',
        ),
        migrations.DeleteModel(
            name='AuthorizedVehicle',
        ),
        migrations.DeleteModel(
            name='GateControlLog',
        ),
        migrations.DeleteModel(
            name='SystemSettings',
        ),
        migrations.DeleteModel(
            name='VehicleDetection',
        ),
    ]
